
services:
  mongo:
    image: mongo:7
    container_name: adoptme-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  adoptme:
    image: heckier04/adoptme:latest
    container_name: adoptme-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/backend_final
      - NODE_ENV=production
    depends_on:
      - mongo

volumes:
  mongo_data: